- 👋 Hi, I'm @thais, I'm 18 years old, I'm a beginner in the programming world.
- 👀 I'm interested in creating apps and their look.
- 🌱 I'm learning java
- 📫 How to reach me: tatizac9@gmail.com
- My linkedin : www.linkedin.com/in/thaís-leonardo
